"""ledger system upgrade

Revision ID: 0a456f4d97ca
Revises: 8dc31a639eda
Create Date: 2026-06-11 18:27:45.069929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a456f4d97ca'
down_revision: Union[str, None] = '8dc31a639eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('balance_cached', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_accounts_id'), 'ledger_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_accounts_owner_id'), 'ledger_accounts', ['owner_id'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_owner_id'), 'ledger_entries', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_owner_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_ledger_accounts_owner_id'), table_name='ledger_accounts')
    op.drop_index(op.f('ix_ledger_accounts_id'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###
