"""multi-tenant eaas + ledger wallet

Revision ID: 4bf977ad9c3b
Revises: db5b184447f5
Create Date: 2026-06-11 18:05:27.173006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf977ad9c3b'
down_revision: Union[str, None] = 'db5b184447f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
