"""multi-tenant eaas + ledger wallet

Revision ID: db5b184447f5
Revises: a1e84fcd14a8
Create Date: 2026-06-11 18:04:04.175385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5b184447f5'
down_revision: Union[str, None] = 'a1e84fcd14a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_usage', sa.Column('provider_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_energy_usage_provider_code'), 'energy_usage', ['provider_code'], unique=False)
    op.create_index(op.f('ix_energy_usage_user'), 'energy_usage', ['user'], unique=False)
    op.add_column('transactions', sa.Column('provider_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_provider_code'), 'transactions', ['provider_code'], unique=False)
    op.add_column('wallets', sa.Column('provider_code', sa.String(), nullable=True))
    op.drop_index(op.f('ix_wallets_user'), table_name='wallets')
    op.create_index(op.f('ix_wallets_user'), 'wallets', ['user'], unique=False)
    op.create_index(op.f('ix_wallets_provider_code'), 'wallets', ['provider_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_provider_code'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_user'), table_name='wallets')
    op.create_index(op.f('ix_wallets_user'), 'wallets', ['user'], unique=True)
    op.drop_column('wallets', 'provider_code')
    op.drop_index(op.f('ix_transactions_provider_code'), table_name='transactions')
    op.drop_column('transactions', 'provider_code')
    op.drop_index(op.f('ix_energy_usage_user'), table_name='energy_usage')
    op.drop_index(op.f('ix_energy_usage_provider_code'), table_name='energy_usage')
    op.drop_column('energy_usage', 'provider_code')
    # ### end Alembic commands ###
